# https://docs.travis-ci.com/user/database-setup/#MySQL
# https://docs.travis-ci.com/
language: node_js
node_js:
  - "6.9.5"
services:
  - mysql
  - mongodb
branches:
  only:
    - develop
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - "yarn install"

# after_success: yarn coverage
after_success: 
  - yarn coverage
  - yarn coverage:codecov
# script:
#   - cypress run --record

# services:
#   - redis-server
# services:
#   - mongodb

# before_script:
#   - sleep 15
#   - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'